### ISSUE TITLE
running image built by ./dockerbuild

### ISSUE THREAD

**Issue by SenpaiPlz** [hgop/week2#2]
Im having trouble running the image build by the ./dockerbuild.sh script. This is the error that is reported onsh both a fresh aws instance and local machine.

postgres_1  | 2017-12-07 09:12:34.783 UTC [1] LOG:  database system is ready to accept connections
server_1    | 
server_1    | > an-outlandish-mean-app@1.0.0 migratedb /server
server_1    | > db-migrate --config ./server/database.json --migrations-dir ./server/migrations up
server_1    | 
server_1    | events.js:136
server_1    |       throw er; // Unhandled 'error' event
server_1    |       ^
server_1    | 
server_1    | Error: connect ECONNREFUSED 127.0.0.1:5432
server_1    |     at Object._errnoException (util.js:1031:13)
server_1    |     at _exceptionWithHostPort (util.js:1052:20)
server_1    |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1195:14)
server_1    | npm ERR! code ELIFECYCLE
server_1    | npm ERR! errno 1
server_1    | npm ERR! an-outlandish-mean-app@1.0.0 migratedb: `db-migrate --config ./server/database.json --migrations-dir ./server/migrations up`
server_1    | npm ERR! Exit status 1
server_1    | npm ERR! 
server_1    | npm ERR! Failed at the an-outlandish-mean-app@1.0.0 migratedb script.
server_1    | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
server_1    | 
server_1    | npm ERR! A complete log of this run can be found in:
server_1    | npm ERR!     /root/.npm/_logs/2017-12-07T09_12_43_930Z-debug.log
provisioning_server_1 exited with code 1

When running the ./runserver directly in the build dir or even the source dir causes this error:

:~/week2/build$ ./runserver.sh 

> an-outlandish-mean-app@1.0.0 migratedb /home/megumin/week2/build
> db-migrate --config ./server/database.json --migrations-dir ./server/migrations up

[INFO] No migrations to run
[INFO] Done
module.js:544
    throw err;
    ^

Error: Cannot find module 'server/globals'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at /home/megumin/week2/build/run.js:2:5
    at Object.<anonymous> (/home/megumin/week2/build/run.js:16:3)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)

I am running on the latest pull from this github.

**Comment by SenpaiPlz** [comment]
Thanks to the TA I have a fix for this.
In the server/database.json you need to change the host from localhost to the name of the postgres contianer.
